<a href="https://colab.research.google.com/github/shreyamali01/COA---Assignment-1/blob/main/COA_2b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#all the elements in the matrix are double
nums = [64,128,256,512,1024]
for i in range(len(nums)):
  p = nums[i]

  #initializing the matrices
  M1 = np.random.uniform(0,10,size=(p,p))
  M2 = np.random.uniform(0,9,size=(p,p))

  #initializing the resultant matrix with zeros
  ans = np.zeros((p,p),dtype=float)

  #matrix multiplication
  for i in range(p):
    for j in range(p):
      for k in range(p):
        ans[i,j] += M1[i,k] * M2[k,j]


  print(M1,'\n')
  print(M2, '\n')
  print(ans, '\n')


[[2.15213481 8.88807746 5.13310541 ... 5.24384977 0.12023428 3.58788337]
 [7.32018903 3.09612404 9.20718117 ... 5.35921458 8.87324841 5.22932982]
 [5.79607207 4.13516979 2.83234149 ... 1.05925782 5.30191206 5.92371311]
 ...
 [4.51200991 0.14817937 6.71238817 ... 8.87391578 1.77398184 5.20046704]
 [1.83243641 5.83967571 4.97721538 ... 8.99973002 1.32768855 8.09387264]
 [2.36359809 5.51747337 7.2654918  ... 6.14854205 5.63814589 8.90341235]] 

[[8.85547367 7.04443827 5.5750357  ... 6.0550063  8.25156586 7.59708371]
 [6.94719635 5.23938838 2.74361711 ... 6.59410925 3.11017419 3.24814456]
 [2.68400607 6.32611054 7.09245061 ... 0.05822314 6.88090017 7.08697161]
 ...
 [0.04713066 4.3160652  1.73015771 ... 3.05956227 7.79729471 1.82886702]
 [6.70170975 0.69238703 0.53867515 ... 0.32960504 7.03457282 8.61845393]
 [8.26262351 3.03418022 6.83440253 ... 3.72514115 1.44531869 8.16870134]] 

[[1373.58682415 1488.59512891 1553.0513182  ... 1479.76358793
  1668.93378998 1604.19906721]
 [1192.88603719

KeyboardInterrupt: 