<a href="https://colab.research.google.com/github/shreyamali01/COA---Assignment-1/blob/main/COA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
nums = [4,2,6,5,3]
for i in range(len(nums)):
  p = nums[i]

  #initializing the matrices
  M1 = np.random.randint(0,9,size=(p,p))
  M2 = np.random.randint(0,9,size=(p,p))

  #initializing the resultant matrix with zeros
  ans = np.zeros((p,p))

  #matrix multiplication
  for i in range(p):
    for j in range(p):
      for k in range(p):
        ans[i,j] += M1[i,k] * M2[k,j]


  print(M1,'\n')
  print(M2, '\n')
  print(ans, '\n')

[[6 5 5 7]
 [5 5 8 4]
 [3 0 4 3]
 [1 8 6 7]] 

[[3 1 5 1]
 [3 1 6 7]
 [0 5 8 8]
 [6 3 1 2]] 

[[ 75.  57. 107.  95.]
 [ 54.  62. 123. 112.]
 [ 27.  32.  50.  41.]
 [ 69.  60. 108. 119.]] 

[[6 5]
 [8 0]] 

[[7 7]
 [5 0]] 

[[67. 42.]
 [56. 56.]] 

[[0 4 3 1 6 0]
 [3 4 5 8 5 1]
 [3 4 6 4 4 7]
 [4 2 5 3 0 1]
 [6 2 1 6 1 2]
 [4 3 5 1 4 7]] 

[[7 4 3 2 3 8]
 [5 1 5 3 1 3]
 [5 4 5 3 4 2]
 [3 5 1 1 7 4]
 [4 0 4 7 3 8]
 [0 1 6 7 8 8]] 

[[ 62.  21.  60.  64.  41.  70.]
 [110.  77.  88.  83. 112. 126.]
 [ 99.  67. 121. 117. 133. 152.]
 [ 72.  54.  56.  39.  63.  68.]
 [ 79.  62.  55.  48.  85. 104.]
 [ 87.  51. 111. 110. 110. 143.]] 

[[5 7 3 2 7]
 [7 1 7 8 6]
 [4 8 5 4 1]
 [7 3 2 6 7]
 [0 7 6 4 8]] 

[[2 1 2 8 5]
 [4 0 0 7 4]
 [2 2 8 4 5]
 [7 1 6 0 4]
 [4 3 7 2 5]] 

[[ 86.  34.  95. 115. 111.]
 [112.  47. 160. 103. 136.]
 [ 82.  21.  79. 110.  98.]
 [100.  38. 115.  99. 116.]
 [100.  40. 128.  89. 114.]] 

[[0 1 5]
 [3 8 4]
 [1 0 4]] 

[[3 6 3]
 [5 3 1]
 [1 6 4]] 

[[10. 33. 21.]
 [53. 66. 3